version: "3.7"

services:
  api_service:
    image: tris97/pet-store-session2:0.0.1
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysql
    links:
      - mysql_db:app_db
  mysql:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: graddb
      MYSQL_ROOT_PASSWORD: 123456