version: "3.7"

services:
  api_service:
    image: tris97/pet-store:0.0.2
    restart: always
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - mysql
    links:
      - mysql:app_db
  mysql:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: graddb
      MYSQL_ROOT_PASSWORD: 123456